name: face_analysis
channels:
  - nvidia # Uncomment this if you want Nvidia GPU support
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - imageio>=2.34.0
  - numpy>=1.26.4
  - pandas>=2.2.0
  - pyarrow>=15.0.0
  # - retina-face>=0.0.14 # Uncomment if you want to use RetinaFaceDetector for face detection
  - scikit-learn>=1.4.1
  - scipy>=1.12.0
  - seaborn>=0.13.2
  - pytorch:pytorch>=2.2.0
  - pytorch-cuda=12.1 # Uncomment this if you want Nvidia GPU support
  - torchvision>=0.17.0
  - torchinfo>=1.8.0
  - tqdm>=4.66.2
  - pip>=24.0
  - pip:
      - facenet-pytorch>=2.5.3
      - matplotlib>=3.8.3
      # - mediapipe>=0.10.9 # Uncomment if you want to use MediaPipe for face detection
      - opencv-python>=4.9.0
