name: face_analysis
channels:
  # - nvidia # Comment this if you don't have an Nvidia GPU
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - imageio>=2.34.0
  - numpy>=1.26.4
  - pandas>=2.2.0
  - pyarrow>=15.0.0
  - scikit-learn>=1.4.1
  - scipy>=1.12.0
  - seaborn>=0.13.2
  - pytorch:pytorch>=2.2.0
  # - pytorch-cuda=12.1 # Comment this if you don't have an Nvidia GPU
  - torchvision>=0.17.0
  - torchinfo>=1.8.0
  - tqdm>=4.66.2
  - pip>=24.0
  - pip:
      - opencv-python>=4.9.0
      - matplotlib>=3.8.3
      - mediapipe>=0.10.9
      - facenet-pytorch>=2.5.3
