name: face_analysis
channels:
  - nvidia # Uncomment this if you have an Nvidia GPU
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - imageio
  - matplotlib
  - mtcnn
  - numpy
  - opencv
  - pandas
  - pyarrow
  - scikit-learn
  - scipy
  - seaborn
  - pytorch:pytorch
  - pytorch-cuda=12.1 # Uncomment this if you have an Nvidia GPU
  - torchvision
  - torchaudio
  - torchinfo
  - tensorflow
  - tqdm
  - pip
  - pip:
      - mediapipe
      - facenet-pytorch
